### ISSUE TITLE
issue 5 -User can search entries list 

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/code-journal#9]
## 📐 Plan
The user can open a search bar that will search through the entries list and filter out entries based on their personalized search.  

## ✅ Task List

- [x]  Add a search icon to the nav.
- [x]  Add a search bar that opens when the icon is pressed. 
- [x]  Create an event listener for search input field
- [x]  Create a function that filters entries based on a search.
- [x]  Verify that only entries that match the search are shown.
- [x]  Create a new data-view - search-view that shows the entries.
- [x]  remove all CSS styling that had no affect or was otherwise unnecessary
- [x]  Fix all errors
